name: Send POST Request and Store JSON Data

on:
  push:
    branches:
      - main

jobs:
  post-request-and-store-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Send POST request and save response
        run: |
          URL="https://jsonplaceholder.typicode.com/posts"
          POST_DATA='{
            "title": "foo",
            "body": "bar",
            "userId": 1
          }'

          # Send the POST request and save the response as JSON
          curl -X POST $URL \
            -H "Content-Type: application/json" \
            -d "$POST_DATA" \
            -o response.json

      - name: Verify response
        run: |
          if [ -f "response.json" ]; then
            echo "POST request successful, response saved as response.json"
          else
            echo "Failed to save response."
            exit 1
          fi

      - name: Upload response as artifact
        uses: actions/upload-artifact@v4
        with:
          name: post-response-json
          path: response.json
