name: Capture Data and Save as JSON

on:
  push:
    branches:
      - main

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create a ZIP file (if needed)
        run: zip -r post-response-json.zip response.json  # Assuming you want to ZIP the file before uploading

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: post-response-json  # Make sure this name matches exactly with what you're using in Workflow 2
          path: post-response-json.zip
