name: Use JSON Data from Previous Workflow

on:
  workflow_run:
    workflows: ["Send POST Request and Store JSON Data"]
    types:
      - completed

jobs:
  download-and-process-json:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Download the artifact containing the JSON response
      - name: Download post-response-json artifact
        uses: actions/download-artifact@v4
        with:
          name: post-response-json

      # Step 2: Process the JSON data (e.g., extract title)
      - name: Extract title from JSON response
        run: |
          # Install jq if not already installed
          sudo apt-get install jq

          # Extract the title from the response JSON
          TITLE=$(jq -r '.title' post-response-json/response.json)

          echo "Extracted Title: $TITLE"

      # Step 3: Optionally use the extracted data or process further
      - name: Use the extracted data
        run: |
          # Example: Print the extracted data (title)
          echo "Title extracted: $TITLE"
