name: Process JSON from post-response-json.zip Artifact

on:
  workflow_run:
    workflows: ["Capture Data and Save as JSON"]
    types:
      - completed

jobs:
  process-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download ZIP artifact from Workflow 1
        uses: actions/download-artifact@v4
        with:
          name: post-response-json

      - name: Unzip the artifact
        run: |
          unzip post-response-json.zip

      - name: Process JSON data
        run: |
          # Ensure the JSON file was extracted
          if [ -f "response.json" ]; then
            echo "JSON file extracted successfully!"
          else
            echo "JSON file not found!"
            exit 1
          fi
          
          # Parse the JSON file to extract specific data
          title=$(jq -r '.title' response.json)
          body=$(jq -r '.body' response.json)
          
          # Output the captured data
          echo "Title: $title"
          echo "Body: $body"
          
          # Store the data into a new JSON file
          echo "{\"title\": \"$title\", \"body\": \"$body\"}" > processed_data.json

      - name: Upload processed data as artifact
        uses: actions/upload-artifact@v4
        with:
          name: processed-data
          path: processed_data.json
